feat(tags): rework of convert case answers to zeep dict
helsingborg-stad/helsingborg-viva-api-adapter pull request #22
Opened 2021-02-15 14:09 UTC by TeddyAndersson

The generation of a zeep dict that creates the soap request to send to VIVA was not desirable. Therefore
changes have been made to the convert function in order to better handle the creation of a zeep dict from tagged
answers.

The rework of the function that converts the case answers to a zeep dict contains the following:
Instead of first iterating over the answers to build up the zeep dict, we iterate over the root keys that the zeep dict should contain. Then we filter the all answers that contains a tag that matches the current root key and iterate over them to create the values for the current root key.

What we get:
```    "answers": [
    {
        "field": {
            "tags": [
                "expenses",
                "boende",
                "date",
               "coapplicant"
            ]
        },
        "value": 1601994748326
    },
    {
        "field": {
            "tags": [
                "expenses",
                "boende",
                "amount",
                "coapplicant"
            ]
        },
        "value": 8760
    },
]
```

What we generate:
```{
        "EXPENSES": [
            {
            "EXPENSE": {
                "TYPE": "boende",
                "DESCRIPTION": "avtal",
                "APPLIESTO": "coapplicant",
                "FREQUENCY": 12,
                "PERIOD": "2020-05-01 - 2020-05-31",
                "AMOUNT": 8760,
                "DATE": "2020-05-08"
            }
      
            }
        ],
        ..
        ..
        ..
}
```

2021-02-15 15:03 UTC, helsingborgsstad commented
Task linked: [CU-dh4pyx VADA - Utgifter och inkomster ska skickas enligt VIVA-SOAP API XML struktur till VIVA för att handläggare ska kunna infoga värden vid beräkning](https://app.clickup.com/t/dh4pyx)

2021-02-15 21:57 UTC, dannil76 approved these changes
Bra jobbat!

2021-02-15 21:57 UTC, dannil76 commented on app/libs/classes/viva_application.py
> +        # valid_tag_values=['date', 'amount']
Ta bort kommenterad kod. Eller den ska användas?

2021-02-15 21:57 UTC, dannil76 commented on app/libs/classes/viva_application.py
> +            # filter by tag value
Kanske funktion som beskriver det du säger i kommentaren?

2021-02-16 22:07 UTC, dannil76 requested changes
Fundersam om svaret verkligen stämmer. Du neggar ID i field. Dessa ID'n kommer med i answer-objektet som lambda: submitApplication postar. Har fungerat tidigare?!

<img width="1792" alt="Skärmavbild 2021-02-16 kl  23 04 01" src="https://user-images.githubusercontent.com/768077/108127596-c0b8ff00-70ab-11eb-9023-b62807bb6bc2.png">

2021-02-16 22:07 UTC, dannil76 commented on app/libs/classes/viva_application.py
> +        return self._helpers.serialize_object(response)
missing new line EOF :)

2021-02-16 22:08 UTC, dannil76 commented
Gör gärna en rebase dev -> din branch

2021-02-17 13:18 UTC, TeddyAndersson commented
> Fundersam om svaret verkligen stämmer. Du neggar ID i field. Dessa ID'n kommer med i answer-objektet som lambda: submitApplication postar. Har fungerat tidigare?!
> 
> <img alt="Skärmavbild 2021-02-16 kl 23 04 01" width="1792" src="https://user-images.githubusercontent.com/768077/108127596-c0b8ff00-70ab-11eb-9023-b62807bb6bc2.png">

Jag har inte ändrat något i valideringen för application, endast behandlat datan. Ska kolla vad som sker (y)

2021-02-17 14:00 UTC, dannil76 approved these changes

2021-02-18 07:52 UTC, merged