feat: 🎸 add endpoint workflow latest
helsingborg-stad/helsingborg-viva-api-adapter pull request #49
Opened 2021-12-19 20:32 UTC by dannil76

## Explain the changes you’ve made
Added new endpoint `mypages/[hashid]/workflows/latest`

## Explain why these changes are made
To be able to check whether a case should be supplemented

## Explain your solution
Added new method - `get_workflow_latest` to the class VivaMyPages, who returns a case that is always the most recent

## How to test the changes?
1. check out branch
2. run `./server.sh`
3. Use Postman or alike and execute an GET request ie: `http://localhost:5000/mypages/[hasid]/workflows/latest`
You should receive one workflow object ie. the latest.

2021-12-19 20:33 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-off.svg) Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* ![Code issue](https://app.embold.io/assets/images/svg/code-issue.svg) 7 Code issues 

 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/0e85314a10805388831e336b2103fb2b/pull-request/49)

2021-12-19 20:49 UTC, helsingborgsstad commented
Task linked: [CU-1pdvmgb Lägg till endpoint i VADA för att hämta ut senaste workflow](https://app.clickup.com/t/1pdvmgb)

2021-12-20 13:20 UTC, TeddyAndersson requested changes
Find some minor changes, also missing tests. But not sure how to write test for flask-restful resources, would be good to start doing it though (y)

2021-12-20 13:20 UTC, TeddyAndersson commented on app/libs/classes/viva_my_pages.py
> +            raise Fault(message='No workflow latset found', code=404)
This error message has incorrect english grammar.
Suggestion: "There was no workflow to be found" or "No workflow was found"

2021-12-20 13:20 UTC, TeddyAndersson commented on app/routes/my_pages_workflow_latest.py
> +    def _get_workflow_latest(self):
This function name has incorrect english grammar
```suggestion
    def _get_latest_workflow(self):
```

2021-12-20 13:20 UTC, TeddyAndersson commented on app/routes/my_pages_workflow_latest.py
> +        return self._get_workflow_latest()
Do we need to separate these functions ie get -> _get_workflow_latest, could we not simply cover everything in the get function? Then we would not need to concern about assigning values to `self`

2021-12-20 13:20 UTC, TeddyAndersson commented on app/routes/my_pages_workflow_latest.py
> +        return self._get_workflow_latest()
Or is there a good reason for doing this ie flask-restful convention etc?

2021-12-22 09:57 UTC, TeddyAndersson approved these changes
Looks good ship it 🚀

2021-12-22 11:05 UTC, merged