Fix/sms notification
helsingborg-stad/helsingborg-viva-api-adapter pull request #53
Opened 2022-01-18 18:37 UTC by dannil76

## Explain the changes you’ve made
Fixed the implementation generating sms notifications.

## Explain your solution
The generated notification object need the keys to be uppercase for Viva to be able to work.

## How to test the changes?
1. Checkout this branch
2. Start the python development server
```BASH
./server.sh
```
3. Replace `###mobile_number###` with the phone number you want to receive the SMS to
4. Replace `###hashid###` with a test person found in Viva admin
```JSON
{
  "applicationType": "recurrent",
  "hashid": "`###hashid###",
  "workflowId": "",
  "answers": [
    {
      "field": {
        "id": "personalInfo.telephone",
        "tags": [
          "phonenumber",
          "applicant"
        ]
      },
      "value": "###mobile_number###"
    },
    {
      "field": {
        "id": "partnerInfo.telephone",
        "tags": [
          "phonenumber",
          "coapplicant"
        ]
      },
      "value": "###mobile_number###"
    },
    {
      "field": {
        "id": "notifyMe",
        "tags": [
          "nofification",
          "sms",
          "applicant"
        ]
      },
      "value": true
    },
    {
      "field": {
        "id": "partner.notifyMe",
        "tags": [
          "nofification",
          "sms",
          "coapplicant"
        ]
      },
      "value": true
    },
    {
      "field": {
        "id": "hiddenSwish",
        "tags": [
          "expenses",
          "annat",
          "description",
          "group:swish"
        ]
      },
      "value": "Swish"
    },
    {
      "field": {
        "id": "swish",
        "tags": [
          "expenses",
          "annat",
          "amount",
          "group:swish"
        ]
      },
      "value": "200"
    }
  ],
  "rawDataType": "pdf",
  "rawData": ""
}
```

3. Make an POST request using endpoint: `http://localhost:5000/applications`, with the playload above as body.

Remeber that you have to supply the correct token for `x-api-key` to make this work.

2022-01-18 18:37 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/0e85314a10805388831e336b2103fb2b/pull-request/53)

2022-01-21 12:51 UTC, MasterKenth requested changes
Very minor comment, otherwise tested and working

2022-01-21 12:51 UTC, MasterKenth commented on app/libs/classes/viva_application.py
> +            for answer in answers:
We could clean this up a tiny bit by removing the `if`:

```python
for answer in answers or []:
```

2022-01-21 13:24 UTC, MasterKenth approved these changes

2022-01-21 13:27 UTC, merged