Feat/new application attachment
helsingborg-stad/helsingborg-viva-api-adapter pull request #61
Opened 2022-05-19 14:02 UTC by dannil76

Lagt till logik som gör det möjligt att posta in bilagor tillsammans med grundansökan

2022-05-19 14:03 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/0e85314a10805388831e336b2103fb2b/pull-request/61)

2022-05-19 14:04 UTC, helsingborgsstad commented
Task linked: [CU-2349fjn VADA ska ta emot bifogade filer tillsammans med grundansökan](https://app.clickup.com/t/2349fjn)

2022-05-20 08:44 UTC, MasterKenth requested changes

2022-05-20 08:44 UTC, MasterKenth commented on app/libs/classes/viva_application.py
> +        attachment_list = self._get_completion_attachments()
We can probably remove `_completion` from the name of every attachment function now that attachments are not strictly connected to a completion.

2022-05-24 13:10 UTC, MasterKenth requested changes

2022-05-25 09:39 UTC, MasterKenth approved these changes

2022-05-25 09:41 UTC, merged